/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedVendedorRouteImport } from './routes/_authenticated/vendedor'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin.clientes'
import { Route as AuthenticatedAdminComercialRouteImport } from './routes/_authenticated/admin.comercial'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin.configuracoes'
import { Route as AuthenticatedAdminEstoqueRouteImport } from './routes/_authenticated/admin.estoque'
import { Route as AuthenticatedAdminImpressaoRouteImport } from './routes/_authenticated/admin.impressao'
import { Route as AuthenticatedAdminVendedoresRouteImport } from './routes/_authenticated/admin.vendedores'
import { Route as AuthenticatedAdminClienteCompanyIdRouteImport } from './routes/_authenticated/admin.cliente.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendedorRoute = AuthenticatedVendedorRouteImport.update({
  id: '/vendedor',
  path: '/vendedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComercialRoute =
  AuthenticatedAdminComercialRouteImport.update({
    id: '/comercial',
    path: '/comercial',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEstoqueRoute =
  AuthenticatedAdminEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminImpressaoRoute =
  AuthenticatedAdminImpressaoRouteImport.update({
    id: '/impressao',
    path: '/impressao',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendedoresRoute =
  AuthenticatedAdminVendedoresRouteImport.update({
    id: '/vendedores',
    path: '/vendedores',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClienteCompanyIdRoute =
  AuthenticatedAdminClienteCompanyIdRouteImport.update({
    id: '/cliente/$companyId',
    path: '/cliente/$companyId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/painel': typeof AuthenticatedPainelRoute
  '/vendedor': typeof AuthenticatedVendedorRoute
  '/q/$code': typeof QCodeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/comercial': typeof AuthenticatedAdminComercialRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/impressao': typeof AuthenticatedAdminImpressaoRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/cliente/$companyId': typeof AuthenticatedAdminClienteCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/vendedor': typeof AuthenticatedVendedorRoute
  '/q/$code': typeof QCodeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/admin/comercial': typeof AuthenticatedAdminComercialRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/admin/impressao': typeof AuthenticatedAdminImpressaoRoute
  '/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/cliente/$companyId': typeof AuthenticatedAdminClienteCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/vendedor': typeof AuthenticatedVendedorRoute
  '/q/$code': typeof QCodeRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin/comercial': typeof AuthenticatedAdminComercialRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/estoque': typeof AuthenticatedAdminEstoqueRoute
  '/_authenticated/admin/impressao': typeof AuthenticatedAdminImpressaoRoute
  '/_authenticated/admin/vendedores': typeof AuthenticatedAdminVendedoresRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/cliente/$companyId': typeof AuthenticatedAdminClienteCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/admin'
    | '/painel'
    | '/vendedor'
    | '/q/$code'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/comercial'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/impressao'
    | '/admin/vendedores'
    | '/admin/'
    | '/admin/cliente/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/painel'
    | '/vendedor'
    | '/q/$code'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/comercial'
    | '/admin/configuracoes'
    | '/admin/estoque'
    | '/admin/impressao'
    | '/admin/vendedores'
    | '/admin'
    | '/admin/cliente/$companyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/_authenticated/admin'
    | '/_authenticated/painel'
    | '/_authenticated/vendedor'
    | '/q/$code'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/clientes'
    | '/_authenticated/admin/comercial'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/estoque'
    | '/_authenticated/admin/impressao'
    | '/_authenticated/admin/vendedores'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/cliente/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  QCodeRoute: typeof QCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendedor': {
      id: '/_authenticated/vendedor'
      path: '/vendedor'
      fullPath: '/vendedor'
      preLoaderRoute: typeof AuthenticatedVendedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clientes': {
      id: '/_authenticated/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/comercial': {
      id: '/_authenticated/admin/comercial'
      path: '/comercial'
      fullPath: '/admin/comercial'
      preLoaderRoute: typeof AuthenticatedAdminComercialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/estoque': {
      id: '/_authenticated/admin/estoque'
      path: '/estoque'
      fullPath: '/admin/estoque'
      preLoaderRoute: typeof AuthenticatedAdminEstoqueRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/impressao': {
      id: '/_authenticated/admin/impressao'
      path: '/impressao'
      fullPath: '/admin/impressao'
      preLoaderRoute: typeof AuthenticatedAdminImpressaoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendedores': {
      id: '/_authenticated/admin/vendedores'
      path: '/vendedores'
      fullPath: '/admin/vendedores'
      preLoaderRoute: typeof AuthenticatedAdminVendedoresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cliente/$companyId': {
      id: '/_authenticated/admin/cliente/$companyId'
      path: '/cliente/$companyId'
      fullPath: '/admin/cliente/$companyId'
      preLoaderRoute: typeof AuthenticatedAdminClienteCompanyIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminComercialRoute: typeof AuthenticatedAdminComercialRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminEstoqueRoute: typeof AuthenticatedAdminEstoqueRoute
  AuthenticatedAdminImpressaoRoute: typeof AuthenticatedAdminImpressaoRoute
  AuthenticatedAdminVendedoresRoute: typeof AuthenticatedAdminVendedoresRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminClienteCompanyIdRoute: typeof AuthenticatedAdminClienteCompanyIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminComercialRoute: AuthenticatedAdminComercialRoute,
  AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
  AuthenticatedAdminEstoqueRoute: AuthenticatedAdminEstoqueRoute,
  AuthenticatedAdminImpressaoRoute: AuthenticatedAdminImpressaoRoute,
  AuthenticatedAdminVendedoresRoute: AuthenticatedAdminVendedoresRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminClienteCompanyIdRoute:
    AuthenticatedAdminClienteCompanyIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedVendedorRoute: typeof AuthenticatedVendedorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedVendedorRoute: AuthenticatedVendedorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  EntrarRoute: EntrarRoute,
  QCodeRoute: QCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
